# apps/ms-geo/Dockerfile
FROM node:20

# Define o diretório de trabalho na raiz do Turborepo
WORKDIR /usr/src/app

# Copia o package.json e o package-lock.json do Turborepo para a raiz
COPY package.json package-lock.json ./

# Instala as dependências compartilhadas do Turborepo
RUN npm install

# Define o diretório de trabalho específico para a aplicação ms-geo
WORKDIR /usr/src/app/ms-geo

# Copia o package.json e o package-lock.json específicos do ms-geo
COPY apps/ms-geo/package.json ./package.json

# Instala as dependências específicas do ms-geo
RUN npm install

# Copia o restante dos arquivos da aplicação ms-geo
COPY apps/ms-geo/ .

# Define o comando para iniciar a aplicação
CMD ["npm", "run", "dev"]
