FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

WORKDIR /usr/src/app/ms-geo

COPY apps/ms-geo/package.json ./package.json

RUN npm install

COPY apps/ms-geo/ .

CMD ["npm", "run", "dev"]
