services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    container_name: redis

  gateway_service:
    build:
      context: "."
      dockerfile: ./apps/ms-gateway/dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - redis
      - weather_service
      - geo_service
      - database_service
    environment:
      - NODE_ENV=development
    #develop:
    #  watch:
    #    - action: sync
    #      path: ./apps/ms-gateway
    #      target: /usr/src/app/ms-gateway
    #      ignore:
    #        - node_modules/
    #    - action: rebuild
    #      path: package.json
    container_name: ms-gateway

  weather_service:
    build:
      context: "."
      dockerfile: ./apps/ms-weather/dockerfile
    env_file:
      - ./apps/ms-weather/.env
    depends_on:
      - redis
      - database_service
      - geo_service
    environment:
      - NODE_ENV=development
    #develop:
    #  watch:
    #    - action: sync
    #      path: ./apps/ms-weather
    #      target: /usr/src/app/ms-weather
    #      ignore:
    #        - node_modules/
    #    - action: rebuild
    #      path: package.json
    container_name: ms-weather

  geo_service:
    build:
      context: "."
      dockerfile: ./apps/ms-geo/dockerfile
    env_file:
      - ./apps/ms-geo/.env
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
    #develop:
    #  watch:
    #    - action: sync
    #      path: ./apps/ms-geo
    #     target: /usr/src/app/ms-geo
    #      ignore:
    #        - node_modules/
    #    - action: rebuild
    #      path: package.json
    container_name: ms-geo

  database_service:
    build:
      context: "."
      dockerfile: ./apps/ms-database/dockerfile
    env_file:
      - ./apps/ms-database/.env
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
    #develop:
    #  watch:
    #    - action: sync
    #      path: ./apps/ms-database
    #      target: /usr/src/app/ms-database
    #      ignore:
    #        - node_modules/
    #    - action: rebuild
    #      path: package.json
    container_name: ms-database
