# apps/ms-weather/Dockerfile
FROM node:20-alpine

# Define o diretório de trabalho na raiz do Turborepo
WORKDIR /usr/src/app

# Copia o package.json e o package-lock.json do Turborepo para a raiz
COPY package.json package-lock.json ./

# Instala as dependências compartilhadas do Turborepo
RUN npm install

# Define o diretório de trabalho específico para a aplicação ms-weather
WORKDIR /usr/src/app/ms-weather

# Copia o package.json e o package-lock.json específicos do ms-weather
COPY apps/ms-weather/package.json ./package.json

# Instala as dependências específicas do ms-weather
RUN npm install

# Copia o restante dos arquivos da aplicação ms-weather
COPY apps/ms-weather/ .

# Define o comando para iniciar a aplicação
CMD ["npm", "run", "dev"]
