FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

WORKDIR /usr/src/app/ms-weather

COPY apps/ms-weather/package.json ./package.json

RUN npm install

COPY apps/ms-weather/ .

CMD ["npm", "run", "dev"]
