# Base menor para reduzir o tamanho da imagem final
FROM node:20-alpine

# Define o diretório de trabalho na raiz do Turborepo
WORKDIR /usr/src/app

# Copia apenas os arquivos necessários para instalar as dependências do monorepo
COPY package.json package-lock.json ./

# Instala as dependências compartilhadas do Turborepo
RUN npm install 

# Define o diretório de trabalho específico para a aplicação ms-gateway
WORKDIR /usr/src/app/ms-gateway

# Copia os arquivos específicos do ms-gateway
COPY apps/ms-gateway/package.json ./

# Instala apenas as dependências do ms-gateway
RUN npm install

# Copia o restante dos arquivos do ms-gateway
COPY apps/ms-gateway/ .

# Expõe a porta usada pela aplicação
EXPOSE 3000

# Define o comando para iniciar a aplicação
CMD ["npm", "run", "start"]
