FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install 

WORKDIR /usr/src/app/ms-gateway

COPY apps/ms-gateway/package.json ./

RUN npm install

COPY apps/ms-gateway/ .

EXPOSE 3000

CMD ["npm", "run", "start"]
