FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install

WORKDIR /usr/src/app/ms-database

COPY apps/ms-database/package.json ./package.json

RUN npm install

COPY apps/ms-database/ .

CMD ["npm", "run", "dev"]
